spring.application.name=cinelog

server.port=8092

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/testdb
spring.datasource.username=green
spring.datasource.password=1234

# /uploads/파일명 → C:/Dev/WS_sts/cinelog/uploads/파일명 으로 매핑
spring.web.resources.static-locations=classpath:/static/,file:///C:/Dev/WS_sts/cinelog/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.thymeleaf.cache=false